force-app/main/default/objects/Currency_Cache__c/Currency_Cache__c.object-meta.xml
<CustomObject>
    <description>Object to store the currencies rates and the time when we retrieved.
So if we want to retrieve a currency that we have retrieved recently we use the rate from this custom metadata cache, so we not reach the limit of the API.
The time to update the rate is in the custom metadata settings</description>
    <label>Currency Cache</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency Cache</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Currency_Cache__c/fields/Iso_Code__c.field-meta.xml
<CustomField>
    <fullName>Iso_Code__c</fullName>
    <description>Iso code of the currency</description>
    <label>Iso Code</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Currency_Cache__c/fields/rate__c.field-meta.xml
<CustomField>
    <fullName>rate__c</fullName>
    <description>Rate of the currency</description>
    <label>rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Currency_Cache__c/fields/TimeStamp_Last_Update__c.field-meta.xml
<CustomField>
    <fullName>TimeStamp_Last_Update__c</fullName>
    <description>Timestamp when the cache rate was last updated</description>
    <label>TimeStamp Last Update</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exchange__c/Exchange__c.object-meta.xml
<CustomObject>
    <description>Object created to save exanges</description>
    <label>Exchange</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchanges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Field where the currency is going to be selected</description>
    <inlineHelpText>Select the currency</inlineHelpText>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFN</fullName>
                <label>Afghan Afghani</label>
            </value>
            <value>
                <fullName>ALL</fullName>
                <label>Albanian Lek</label>
            </value>
            <value>
                <fullName>DZD</fullName>
                <label>Algerian Dinar</label>
            </value>
            <value>
                <fullName>ARS</fullName>
                <label>Argentine Peso</label>
            </value>
            <value>
                <fullName>AMD</fullName>
                <label>Armenian Dram</label>
            </value>
            <value>
                <fullName>AUD</fullName>
                <label>Australian Dollar</label>
            </value>
            <value>
                <fullName>AZN</fullName>
                <label>Azerbaijani Manat</label>
            </value>
            <value>
                <fullName>BHD</fullName>
                <label>Bahraini Dinar</label>
            </value>
            <value>
                <fullName>BDT</fullName>
                <label>Bangladeshi Taka</label>
            </value>
            <value>
                <fullName>BYN</fullName>
                <label>Belarusian Ruble</label>
            </value>
            <value>
                <fullName>BZD</fullName>
                <label>Belize Dollar</label>
            </value>
            <value>
                <fullName>BOB</fullName>
                <label>Bolivian Boliviano</label>
            </value>
            <value>
                <fullName>BAM</fullName>
                <label>Bosnia-Herzegovina Convertible Mark</label>
            </value>
            <value>
                <fullName>BWP</fullName>
                <label>Botswanan Pula</label>
            </value>
            <value>
                <fullName>BRL</fullName>
                <label>Brazilian Real</label>
            </value>
            <value>
                <fullName>GBP</fullName>
                <label>British Pound Sterling</label>
            </value>
            <value>
                <fullName>BND</fullName>
                <label>Brunei Dollar</label>
            </value>
            <value>
                <fullName>BGN</fullName>
                <label>Bulgarian Lev</label>
            </value>
            <value>
                <fullName>BIF</fullName>
                <label>Burundian Franc</label>
            </value>
            <value>
                <fullName>KHR</fullName>
                <label>Cambodian Riel</label>
            </value>
            <value>
                <fullName>CAD</fullName>
                <label>Canadian Dollar</label>
            </value>
            <value>
                <fullName>CVE</fullName>
                <label>Cape Verdean Escudo</label>
            </value>
            <value>
                <fullName>XOF</fullName>
                <label>CFA Franc BCEAO</label>
            </value>
            <value>
                <fullName>XAF</fullName>
                <label>CFA Franc BEAC</label>
            </value>
            <value>
                <fullName>CLP</fullName>
                <label>Chilean Peso</label>
            </value>
            <value>
                <fullName>CNY</fullName>
                <label>Chinese Yuan</label>
            </value>
            <value>
                <fullName>COP</fullName>
                <label>Colombian Peso</label>
            </value>
            <value>
                <fullName>KMF</fullName>
                <label>Comorian Franc</label>
            </value>
            <value>
                <fullName>CDF</fullName>
                <label>Congolese Franc</label>
            </value>
            <value>
                <fullName>CRC</fullName>
                <label>Costa Rican Colón</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange__c/fields/exchange_rate__c.field-meta.xml
<CustomField>
    <fullName>exchange_rate__c</fullName>
    <description>Float number to story the exchange rate from the currency</description>
    <label>exchange rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Settings__mdt/Settings__mdt.object-meta.xml
<CustomObject>
    <description>Settings metadata where to store the different configuration settings from our platform</description>
    <label>Settings</label>
    <pluralLabel>Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Settings__mdt/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <description>Time in milliseconds that we want the rate to expire</description>
    <label>Timestamp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Settings__mdt/fields/TimeStamp_Last_Update__c.field-meta.xml
<CustomField>
    <fullName>TimeStamp_Last_Update__c</fullName>
    <description>Timestamp from last update of the currencies in the cache</description>
    <label>TimeStamp Last Update</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExchangeTriggerHandlerTest.cls
@IsTest
private class ExchangeTriggerHandlerTest {
    
    @IsTest
    private static void retrieveRate_success(){
        //Given
        List<Exchange__c> newExchangeList = new List<Exchange__c>();
        Exchange__c exchange = new Exchange__c();
        exchange.Currency__c = 'GBP';
        newExchangeList.add(exchange);

        Currency_Cache__c cache = new Currency_Cache__c();
        cache.TimeStamp_Last_Update__c = System.currentTimeMillis();
        cache.Iso_Code__c = 'GBP';
        cache.rate__c = 1.1;
        insert cache;

        Settings__mdt setting = new Settings__mdt();
        setting.Timestamp__c = 86400000;

        //When
        Test.startTest();
        insert newExchangeList;
        Test.stopTest();

        //Then
        List<Exchange__c> exchangeList = [Select Id, exchange_rate__c, Currency__c from Exchange__c];
        System.AssertEquals(1, exchangeList.size(), 'There should be one exchange record inserted');
        System.AssertEquals('GBP', exchangeList.get(0).Currency__c, 'There currency should be GBP');
        System.AssertEquals(1.1, exchangeList.get(0).exchange_rate__c, 'There rate should be 1.1');
    }

    @IsTest
    private static void retrieveRate_Fail_loadingRates(){
        //Given
        Test.setMock(HttpCalloutMock.class, new getExchangeSuccess());
        List<Exchange__c> newExchangeList = new List<Exchange__c>();
        Exchange__c exchange = new Exchange__c();
        exchange.Currency__c = 'GBP';
        newExchangeList.add(exchange);

        Currency_Cache__c cache = new Currency_Cache__c();
        cache.TimeStamp_Last_Update__c = 10;
        cache.Iso_Code__c = 'GBP';
        cache.rate__c = 1.1;
        insert cache;

        Settings__mdt setting = new Settings__mdt();
        setting.Timestamp__c = 1;

        //When
        Test.startTest();
        insert newExchangeList;
        Test.stopTest();

        //Then
        List<Exchange__c> exchangeList = [Select Id, exchange_rate__c, Currency__c from Exchange__c];
        System.AssertEquals(1, exchangeList.size(), 'There should be one exchange record inserted');
        System.AssertEquals('GBP', exchangeList.get(0).Currency__c, 'There currency should be GBP');
        System.AssertEquals(null, exchangeList.get(0).exchange_rate__c, 'There rate should be 1.1');
    }

    private class getExchangeSuccess implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest request) {
            HttpResponse response = new HttpResponse();
            response.setStatusCode(200);
            response.setBody('{"success": true,"timestamp": 1674683463,"base": "EUR","date": "2023-01-25","rates": {"GBP": 1.10}}');
            return response;
        }
    }

}