force-app/main/default/objects/API_Logs__c/API_Logs__c.object-meta.xml
<CustomObject>
    <description>Object to store the logs of api calls</description>
    <label>API Logs</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Logs__c/fields/Body_Result__c.field-meta.xml
<CustomField>
    <fullName>Body_Result__c</fullName>
    <description>Body result of the callout</description>
    <label>Body Result</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_Logs__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint call</description>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Logs__c/fields/status_code__c.field-meta.xml
<CustomField>
    <fullName>status_code__c</fullName>
    <description>field to store the status code of the call</description>
    <label>status code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/API_Logs__c/fields/Success__c.field-meta.xml
<CustomField>
    <fullName>Success__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to indicate if the result of the callout is successful</description>
    <label>Success</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ExchangeRatesConnection.cls
public with sharing class ExchangeRatesConnection implements IExchangeRatesConnector{

    private static IExchangeRatesConnector connectorInstance;
    
    public class ExchangeRateResult{
        public Boolean success {get; set;}
        public Integer timestamp {get; set;}
        public String base {get; set;}
        public Map<String, Double> rates {get; set;}
        public Map<String, String> error {get; set;}
    }


    public interface IExchangeRatesConnector {
        ExchangeRateResult retrieveLatestExchangeRate(Set<String> currenciesISOSet);
    }

    //Singleton patern
    public static IExchangeRatesConnector getInstance() {
        if (connectorInstance == null) {
            connectorInstance = new ExchangeRatesConnection();
        }
        return connectorInstance;
    }

    public ExchangeRateResult retrieveLatestExchangeRate(Set<String> currenciesISOSet){
        ExchangeRateResult result = new ExchangeRateResult();
        result.success = false;

        API_Logs__c apilog = new API_Logs__c();
        HttpRequest req = new HttpRequest();
        try{
            req.setEndpoint('callout:ExchangeRatesNamedCredential/latest?symbols='+String.join(new List<String>(currenciesISOSet),','));
            req.setMethod('GET');
            Http http = new Http();
            HTTPResponse httpResponse = http.send(req);
            System.debug(httpResponse);
            if (httpResponse.getStatusCode() == 200) {
                JSONParser parser = JSON.createParser(httpResponse.getBody());
                System.debug('Body: '+httpResponse.getBody());
                result = (ExchangeRateResult) JSON.deserialize(httpResponse.getBody(), ExchangeRateResult.class);
                result.success = result.success == null ? false : result.success;
                System.debug('result: '+result);
                //populating apilog data
                apilog.status_code__c = httpResponse.getStatusCode();
                apilog.Success__c = result.success;
                apilog.Body_Result__c = httpResponse.getBody();
                if(result.error != null && !result.error.isEmpty()){
                    System.debug('result.error: '+result.error);        
                }
            }
        } catch (Exception e) {
            apilog.Success__c = false;
            apilog.Body_Result__c = e.getMessage();
        } finally{
            apilog.Endpoint__c = req.getEndpoint();
            insert apilog;
        }

        return result;
    }
}